version: "3.8"

name: artichoke-backend

services:
  mysql:
    container_name: mysql
    build:
      dockerfile: ./mysql.dockerfile
    ports:
      - 6603:3306
    networks:
      - network1
    secrets:
      - db_pass
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_pass # note the _FILE at the end of the name of the environement variable

networks:
  network1:
    name: backend-db
  network2:
    name: backend-http

secrets:
  db_pass:
    file: ./.mysql_db_pass